-- 1) Extensions
create extension if not exists "pgcrypto";
create extension if not exists "vector";

-- 2) Users & Auth Tables (from oauth-schema.sql)

-- Users table (change id from bigint to uuid)
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  email_verified boolean default false,
  phone text unique,
  phone_verified boolean default false,
  full_name text,
  avatar_url text,
  role text default 'customer' check (role in ('customer', 'admin', 'vendor')),
  is_active boolean default true,
  last_sign_in_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- OAuth providers table
create table if not exists public.oauth_providers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade not null,
  provider text not null check (provider in ('google', 'github', 'facebook', 'apple')),
  provider_user_id text not null,
  provider_email text,
  provider_data jsonb,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique(provider, provider_user_id)
);

-- User sessions table
create table if not exists public.user_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade not null,
  session_token text unique not null,
  ip_address inet,
  user_agent text,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default now()
);

-- User profiles table (extended info)
create table if not exists public.user_profiles (
  id uuid primary key references public.users(id) on delete cascade,
  bio text,
  date_of_birth date,
  gender text check (gender in ('male', 'female', 'other', 'prefer_not_to_say')),
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  postal_code text,
  country text,
  preferences jsonb default '{}',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 3) E-Commerce Tables

-- Products table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  specs text,
  price bigint,
  original_price bigint,
  discount integer,
  image text,
  category text,
  brand text,
  in_stock boolean not null default true,
  stock integer not null default 0,
  rating numeric,
  reviews integer,
  embedding vector(768),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_name_idx on public.products using btree (name);
create index if not exists products_category_idx on public.products using btree (category);
create index if not exists products_brand_idx on public.products using btree (brand);
create index if not exists products_embedding_ivfflat_idx
  on public.products using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- Orders table (FIX: change user_id to uuid)
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,  -- ✅ Changed to uuid
  customer jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  subtotal bigint not null default 0,
  discount bigint not null default 0,
  shipping bigint not null default 0,
  total bigint not null default 0,
  promo_code text,
  payment_method text not null default 'cod',
  payment_provider text,
  payment_reference text,
  paid_at timestamptz,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_user_id_idx on public.orders using btree (user_id);
create index if not exists orders_created_at_idx on public.orders using btree (created_at desc);

-- Notification events table
create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  type text not null,
  to_email text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint notification_events_unique unique (order_id, type, to_email)
);

create index if not exists notification_events_to_email_idx on public.notification_events using btree (to_email);
create index if not exists notification_events_created_at_idx on public.notification_events using btree (created_at desc);

-- Carts table (FIX: change user_id to uuid)
create table if not exists public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,  -- ✅ Changed to uuid
  cart_key text unique,
  items jsonb not null default '[]'::jsonb,
  total bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint carts_user_or_key check (
    (user_id is not null and cart_key is null) or
    (user_id is null and cart_key is not null)
  )
);

create index if not exists carts_user_id_idx on public.carts using btree (user_id);

-- 4) Helper Functions

-- Update updated_at timestamp
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Apply triggers
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'update_users_updated_at') then
    create trigger update_users_updated_at before update on public.users
    for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_oauth_providers_updated_at') then
    create trigger update_oauth_providers_updated_at before update on public.oauth_providers
    for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_user_profiles_updated_at') then
    create trigger update_user_profiles_updated_at before update on public.user_profiles
    for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_products_updated_at') then
    create trigger update_products_updated_at before update on public.products
    for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_orders_updated_at') then
    create trigger update_orders_updated_at before update on public.orders
    for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_carts_updated_at') then
    create trigger update_carts_updated_at before update on public.carts
    for each row execute function update_updated_at_column();
  end if;
end $$;

-- 5) Vector Search Function
create or replace function public.match_products(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  name text,
  description text,
  specs text,
  price bigint,
  original_price bigint,
  discount integer,
  image text,
  category text,
  brand text,
  in_stock boolean,
  stock integer,
  rating numeric,
  reviews integer,
  similarity float
)
language sql stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.description,
    p.specs,
    p.price,
    p.original_price,
    p.discount,
    p.image,
    p.category,
    p.brand,
    p.in_stock,
    p.stock,
    p.rating,
    p.reviews,
    (1 - (p.embedding <=> query_embedding))::float as similarity
  from public.products p
  where p.embedding is not null
    and (1 - (p.embedding <=> query_embedding)) >= match_threshold
  order by p.embedding <=> query_embedding
  limit match_count;
$$;

-- 6) Enable RLS (optional but recommended)
alter table public.users enable row level security;
alter table public.oauth_providers enable row level security;
alter table public.user_sessions enable row level security;
alter table public.user_profiles enable row level security;
alter table public.orders enable row level security;
alter table public.carts enable row level security;



-- RLS Policies for orders
create policy "Users can view own orders"
  on public.orders for select
  using (auth.uid() = user_id);

-- RLS Policies for carts
create policy "Users can view own cart"
  on public.carts for select
  using (auth.uid() = user_id);

create policy "Users can update own cart"
  on public.carts for update
  using (auth.uid() = user_id);