-- Supabase schema for Web E-Commerce (Techmart)
-- Apply in Supabase SQL Editor.

-- 1) Extensions
create extension if not exists "pgcrypto";
create extension if not exists "vector";

-- 2) Tables

-- Users for custom cookie-based auth (NOT Supabase Auth).
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  name text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Products table (supports both the demo site and semantic search via embeddings)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  specs text,
  price bigint,
  original_price bigint,
  discount integer,
  image text,
  category text,
  brand text,
  in_stock boolean not null default true,
  stock integer not null default 0,
  rating numeric,
  reviews integer,
  embedding vector(768),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_name_idx on public.products using btree (name);
create index if not exists products_category_idx on public.products using btree (category);
create index if not exists products_brand_idx on public.products using btree (brand);

-- Vector index for semantic search.
-- NOTE: ivfflat requires data distribution; after inserting data run: analyze public.products;
create index if not exists products_embedding_ivfflat_idx
  on public.products using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- Orders (store items/customer as JSONB for flexibility)
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  customer jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  subtotal bigint not null default 0,
  discount bigint not null default 0,
  shipping bigint not null default 0,
  total bigint not null default 0,
  promo_code text,
  payment_method text not null default 'cod',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_user_id_idx on public.orders using btree (user_id);
create index if not exists orders_created_at_idx on public.orders using btree (created_at desc);

-- Email notification events (idempotency + audit)
create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  type text not null,
  to_email text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint notification_events_unique unique (order_id, type, to_email)
);

create index if not exists notification_events_to_email_idx on public.notification_events using btree (to_email);
create index if not exists notification_events_created_at_idx on public.notification_events using btree (created_at desc);

-- Carts (guest carts keyed by cart_key; user carts keyed by user_id)
create table if not exists public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id bigint references public.users(id) on delete cascade,
  cart_key text unique,
  items jsonb not null default '[]'::jsonb,
  total bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint carts_user_or_key check (
    (user_id is not null and cart_key is null) or
    (user_id is null and cart_key is not null)
  )
);

create index if not exists carts_user_id_idx on public.carts using btree (user_id);

-- 3) Helpers

-- Keep updated_at fresh
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'users_set_updated_at') then
    create trigger users_set_updated_at before update on public.users
    for each row execute function public.set_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'products_set_updated_at') then
    create trigger products_set_updated_at before update on public.products
    for each row execute function public.set_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'orders_set_updated_at') then
    create trigger orders_set_updated_at before update on public.orders
    for each row execute function public.set_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'carts_set_updated_at') then
    create trigger carts_set_updated_at before update on public.carts
    for each row execute function public.set_updated_at();
  end if;
end $$;

-- 4) RPC for vector search (used by /api/search and /api/chat)
-- Returns rows + a similarity score (higher is better).
create or replace function public.match_products(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  name text,
  description text,
  specs text,
  price bigint,
  original_price bigint,
  discount integer,
  image text,
  category text,
  brand text,
  in_stock boolean,
  stock integer,
  rating numeric,
  reviews integer,
  similarity float
)
language sql stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.description,
    p.specs,
    p.price,
    p.original_price,
    p.discount,
    p.image,
    p.category,
    p.brand,
    p.in_stock,
    p.stock,
    p.rating,
    p.reviews,
    (1 - (p.embedding <=> query_embedding))::float as similarity
  from public.products p
  where p.embedding is not null
    and (1 - (p.embedding <=> query_embedding)) >= match_threshold
  order by p.embedding <=> query_embedding
  limit match_count;
$$;

-- 5) RLS (optional)
-- This project primarily queries via server routes. If you want to lock down public access,
-- enable RLS and use the service role key in server-only code.
-- alter table public.products enable row level security;
-- alter table public.orders enable row level security;
-- alter table public.carts enable row level security;
-- alter table public.users enable row level security;
