
-- Brands table
CREATE TABLE IF NOT EXISTS public.brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  logo TEXT,
  description TEXT,
  product_count INTEGER DEFAULT 0,
  featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Discounts/Promotions table
CREATE TABLE IF NOT EXISTS public.discounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  code TEXT UNIQUE NOT NULL,
  discount_value BIGINT NOT NULL,
  discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
  valid_until DATE,
  image TEXT,
  min_purchase BIGINT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add update triggers for new tables
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_brands_updated_at') THEN
    CREATE TRIGGER update_brands_updated_at BEFORE UPDATE ON public.brands
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_discounts_updated_at') THEN
    CREATE TRIGGER update_discounts_updated_at BEFORE UPDATE ON public.discounts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

-- INSERT PRODUCTS DATA

INSERT INTO public.products (id, name, description, specs, price, original_price, discount, image, category, brand, in_stock, stock, rating, reviews) VALUES
-- Smartphones
(1, 'iPhone 15 Pro Max', 'Flagship smartphone with titanium design and A17 Pro chip', '256GB - Titan Natural', 29990000, 38000000, 18, 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=300&fit=crop', 'Phone', 'Apple', true, 50, 4.8, 1240),
(2, 'Samsung Galaxy S24 Ultra', 'Ultimate Android flagship with S Pen and AI features', '512GB - Titan Gray', 33990000, 40000000, 15, 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=300&fit=crop', 'Phone', 'Samsung', true, 45, 4.8, 987),
(3, 'iPhone 14 Pro', 'Powerful smartphone with Dynamic Island', '128GB - Deep Purple', 22990000, 27000000, 15, 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-finish-select-202209-6-1inch-deeppurple?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1663703841896', 'Phone', 'Apple', true, 30, 4.7, 856),
(4, 'Google Pixel 8 Pro', 'Pure Android experience with amazing camera', '256GB - Obsidian', 24990000, 28000000, 11, 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=300&fit=crop', 'Phone', 'Google', true, 40, 4.6, 654),
(5, 'Xiaomi 14 Ultra', 'Premium flagship with Leica camera system', '512GB - Black', 26990000, 30000000, 10, 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', 'Phone', 'Xiaomi', true, 35, 4.7, 432),

-- Laptops
(6, 'MacBook Pro 16"', 'Professional laptop with M3 Pro chip for ultimate performance', 'M3 Pro, 512GB SSD', 65990000, 75000000, 12, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=300&fit=crop', 'Laptop', 'Apple', true, 25, 4.9, 856),
(7, 'Dell XPS 15', 'Premium Windows laptop with stunning OLED display', 'Intel i7, 16GB RAM, 512GB SSD', 42990000, 48000000, 10, 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&h=300&fit=crop', 'Laptop', 'Dell', true, 20, 4.6, 534),
(8, 'ASUS ROG Zephyrus G14', 'Powerful gaming laptop in a compact form', 'AMD Ryzen 9, RTX 4060, 16GB', 38990000, 45000000, 13, 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400&h=300&fit=crop', 'Laptop', 'ASUS', true, 18, 4.7, 423),
(9, 'Lenovo ThinkPad X1 Carbon', 'Business ultrabook with legendary keyboard', 'Intel i7, 16GB RAM, 512GB SSD', 35990000, 42000000, 14, 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=300&fit=crop', 'Laptop', 'Lenovo', true, 22, 4.5, 312),

-- AirPods/Headphones
(10, 'AirPods Pro (Gen 3)', 'Premium wireless earbuds with active noise cancellation', 'Active Noise Cancellation', 6490000, 7500000, 13, 'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=400&h=300&fit=crop', 'AirPod', 'Apple', true, 100, 4.7, 2341),
(11, 'Sony WH-1000XM5', 'Industry-leading noise canceling headphones', 'Wireless, 30h battery', 8990000, 10500000, 14, 'https://images.unsplash.com/photo-1545127398-14699f92334b?w=400&h=300&fit=crop', 'AirPod', 'Sony', true, 75, 4.9, 1876),
(12, 'Bose QuietComfort Ultra', 'Premium comfort with exceptional sound', 'Wireless, Noise Cancelling', 9990000, 11500000, 13, 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=300&fit=crop', 'AirPod', 'Bose', true, 60, 4.8, 1234),
(13, 'Samsung Galaxy Buds 2 Pro', 'Premium earbuds for Galaxy ecosystem', 'ANC, 360 Audio', 4490000, 5500000, 18, 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=300&fit=crop', 'AirPod', 'Samsung', true, 80, 4.6, 876),

-- Smartwatches
(14, 'Apple Watch Series 9', 'Advanced health and fitness tracking', '45mm, GPS + Cellular', 12990000, 15000000, 13, 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400&h=300&fit=crop', 'Watch', 'Apple', true, 55, 4.8, 1543),
(15, 'Samsung Galaxy Watch 6', 'Comprehensive health monitoring for Android', '44mm, LTE', 8990000, 10500000, 14, 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=400&h=300&fit=crop', 'Watch', 'Samsung', true, 65, 4.6, 987),
(16, 'Garmin Fenix 7', 'Premium multisport GPS smartwatch', '47mm, Sapphire Solar', 19990000, 23000000, 13, 'https://images.unsplash.com/photo-1557438159-51eec7a6c9e8?w=400&h=300&fit=crop', 'Watch', 'Garmin', true, 30, 4.9, 654),

-- Cameras
(17, 'Sony A7 IV', 'Full-frame mirrorless camera for professionals', '33MP, 4K 60fps', 62990000, 70000000, 10, 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=400&h=300', 'Camera', 'Sony', true, 15, 4.9, 432),
(18, 'Canon EOS R6 Mark II', 'Versatile full-frame for photo and video', '24MP, Dual Pixel AF', 58990000, 65000000, 9, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=300&fit=crop', 'Camera', 'Canon', true, 12, 4.8, 543),

-- Gaming
(19, 'PlayStation 5', 'Next-gen gaming console', '825GB SSD, 4K Gaming', 14990000, 16500000, 9, 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=300&fit=crop', 'Gaming', 'Sony', true, 40, 4.9, 2341),
(20, 'Xbox Series X', 'Most powerful Xbox ever', '1TB SSD, 4K 120fps', 13990000, 15500000, 10, 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=300&fit=crop', 'Gaming', 'Microsoft', true, 35, 4.8, 1987);

-- Reset the sequence for products
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));

-- INSERT BRANDS DATA==

INSERT INTO public.brands (id, name, logo, description, product_count, featured) VALUES
(1, 'Apple', 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg', 'Premium technology products with innovative design and ecosystem', 45, true),
(2, 'Samsung', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Samsung_wordmark.svg', 'Leading electronics manufacturer with diverse product range', 67, true),
(3, 'Dell', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg', 'Trusted brand for laptops and computer hardware', 32, true),
(4, 'Sony', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg', 'Premium audio and entertainment technology', 28, true),
(5, 'Google', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg', 'Innovation in smartphones and smart home devices', 24, false),
(6, 'Microsoft', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg', 'Gaming consoles and productivity devices', 18, false),
(7, 'ASUS', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/ASUS_Logo.svg', 'Gaming laptops and computer hardware', 35, false),
(8, 'Lenovo', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Lenovo_logo_2015.svg', 'Business and consumer computing solutions', 41, false);

-- Reset the sequence for brands
SELECT setval('brands_id_seq', (SELECT MAX(id) FROM brands));

-- INSERT DISCOUNTS DATA


INSERT INTO public.discounts (id, title, description, code, discount_value, discount_type, valid_until, image, min_purchase, is_active) VALUES
(1, 'Flash Sale Weekend', 'Extra 20% off on selected smartphones', 'FLASH20', 20, 'percentage', '2025-11-15', '/placeholder.svg?height=200&width=400', 10000000, true),
(2, 'Laptop Special', 'Get 3,000,000 VND off on laptops over 30M', 'LAPTOP3M', 3000000, 'fixed', '2025-11-30', '/placeholder.svg?height=200&width=400', 30000000, true),
(3, 'Audio Bundle Deal', 'Buy headphones, get 15% off on accessories', 'AUDIO15', 15, 'percentage', '2025-12-10', '/placeholder.svg?height=200&width=400', 5000000, true),
(4, 'New Customer Welcome', '10% off your first purchase', 'WELCOME10', 10, 'percentage', '2025-12-31', '/placeholder.svg?height=200&width=400', 0, true);

-- Reset the sequence for discounts
SELECT setval('discounts_id_seq', (SELECT MAX(id) FROM discounts));

-- Check inserted data
SELECT 'Products count:' as check_type, COUNT(*) as count FROM public.products
UNION ALL
SELECT 'Brands count:', COUNT(*) FROM public.brands
UNION ALL
SELECT 'Discounts count:', COUNT(*) FROM public.discounts;

